# Generated by Django 2.2 on 2020-02-25 18:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Retake_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='thought',
            managers=[
                ('objecs', django.db.models.manager.Manager()),
            ],
        ),
    ]
