# Generated by Django 2.2 on 2020-02-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Retake_app', '0002_auto_20200225_1016'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='thought',
            managers=[
            ],
        ),
    ]
