# Generated by Django 2.2 on 2020-02-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retake_app', '0003_auto_20200225_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='like',
            field=models.ManyToManyField(related_name='liked_thot', to='Retake_app.User'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
