# Generated by Django 2.2 on 2020-02-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retake_app', '0004_auto_20200225_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thought',
            name='like',
        ),
        migrations.AddField(
            model_name='thought',
            name='likes',
            field=models.ManyToManyField(related_name='liked_thots', to='Retake_app.User'),
        ),
    ]
